config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :meals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :meal_time, presence: true
  validate :image_presence

  private

  def image_presence
    errors.add(:image, "を添付してください。") unless image.attached?
  end

  def calculate_co2_reduction
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :meals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :age, :gender])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :age, :gender])
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #before_action :authenticate_user!, only: [:index, :edit, :update, :destroy]

  def index
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]

  def index
    @meals = Meal.order(created_at: :desc)
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    @meal = current_user.meals.new(meal_params)
    if @meal.save
      redirect_to meals_path, notice: '食事情報が投稿されました。'
    else
      render :new
    end
  end

  def show
    @meal = Meal.find(params[:id])
    #@co2_reduction = @meal.calculate_co2_reduction
    #@total_nutrients = @meal.total_nutrients
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def update
    @meal = Meal.find(params[:id])
    if @meal.update(meal_params)
      redirect_to @meal, notice: '食事内容が更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy
    redirect_to meals_path, notice: '食事内容が削除されました。'
  end

  private

  def meal_params
    params.require(:meal).permit(:name, :description, :meal_time, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def show
    #@user = User.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="background-image-wrapper">
  <div class="content d-flex align-items-center justify-content-center">
    <% if user_signed_in? %>
      <div class="text-center">
        <h1>こんにちは、<%= current_user.nickname %>さん！</h1>
        <p>ようこそEcoEatsへ。素晴らしい食事体験をお楽しみください。</p>
      </div>
    <% else %>
      <div class="text-center">
        <h1>EcoEatsへようこそ！</h1>
        <p>健康的で持続可能な食生活を始めましょう。</p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcoEats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-custom">
      <%= link_to "EcoEats", root_path, class: "navbar-brand logo-style" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item active">
            <%= link_to "ホーム", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "食事", meals_path, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to current_user.nickname, edit_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/meals/_form.html.erb
<%= form_with(model: @meal, local: true, html: { multipart: true, 'data-turbo': false, class: "form-horizontal" }) do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h4><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h4>
      <ul>
        <% @meal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-10">
        <div class="form-group mb-4">
          <%= f.label :meal_time, "食事時間" %>
          <%= f.datetime_local_field :meal_time, class: "form-control" %>
        </div>

        <div class="form-group mb-4">
          <%= f.label :image, "画像" %>
          <%= f.file_field :image, id: 'image-input', class: 'form-control-file' %>
          <div id="image-preview" class="mt-3"></div>
        </div>

        <div class="form-group mb-4 custom-width">
          <%= f.label :name, "食事名" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group mb-4 custom-width">
          <%= f.label :description, "説明" %>
          <%= f.text_area :description, class: "form-control" %>
        </div>

        <div class="form-group text-center">
          <%= f.submit "保存", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/meals/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h1 class="my-4 text-center">🌱 <%= @meal.name %>を編集 🌱</h1>
        </div>
        <div class="card-body">
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meals/index.html.erb
<h1 class="my-4 text-center">🌱 食事一覧 🌱</h1>

<div class="text-center my-4">
  <%= link_to '新しい食事を追加', new_meal_path, class: 'btn btn-primary btn-lg' %>
</div>

<div class="row">
  <% if @meals.present? %>
    <% @meals.each do |meal| %>
      <div class="col-md-3 mb-4">
        <div class="card h-100 shadow">
          <% if meal.image.present? %>
            <%= image_tag meal.image, class: "card-img-top img-fluid", style: "height: 300px;" %>
          <% else %>
            <img class="card-img-top img-fluid" src="https://via.placeholder.com/150" alt="Placeholder" style="height: 300px;">
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to meal.name, meal_path(meal) %></h5>
            <p class="card-text"><%= truncate(meal.description, length: 100) %></p>
            <% if meal.meal_time.present? %>
              <p class="card-text"><small class="text-muted"><%= meal.meal_time.strftime('%Y.%-m/%-d %H:%M') %></small></p>
            <% end %>
          </div>
          <div class="card-footer bg-white d-flex justify-content-between">
            <%= link_to '詳細を見る', meal_path(meal), class: "btn btn-outline-primary btn-sm" %>
            <div>
              <%= link_to '編集', edit_meal_path(meal), class: "btn btn-outline-secondary btn-sm me-2" %>
              <%= link_to '削除', meal_path(meal), data: { turbo_method: :delete }, class: "btn btn-outline-danger btn-sm" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="col-12 text-center">
      <p class="my-4">食事情報はありません。</p>
    </div>
  <% end %>
</div>

app/views/meals/new.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center" style="height: 100vh;">
    <div class="col-md-8 col-lg-6">
      <div class="card">
        <div class="card-body">
          <h1 class="my-4 text-center">🌱 新しい食事を追加 🌱</h1>
          <%= render 'form', meal: @meal %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meals/show.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center" style="height: 100vh;">
    <div class="col-md-6">
      <div class="card mt-4">
        <% if @meal.image.attached? %>
          <%= image_tag @meal.image, class: 'img-fluid' %>
        <% else %>
          <img class="card-img-top" src="https://via.placeholder.com/350x150" alt="Placeholder">
        <% end %>
        <div class="card-body">
          <h3 class="card-title"><%= @meal.name %></h3>
          <p class="card-text"><%= @meal.description %></p>
          <!-- ここにCO2削減量や栄養バランスを表示 -->
        </div>
      </div>
    </div>
  </div>
</div>